name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - name: Prepare
        # we don't need to run ./develop.sh
        run: gleam desp download
      - name: Test
        run: gleam test
      - name: Check formatting
        run: gleam format --check src test
